
spring:
  profiles:
    active : local # local(로컬), dev(개발) , prod(운영)  
  #Process Id 파일위치 설정 
  # pid:
  #   file: ex-DApp.pid
  #에러코드정의 파일 설정. 
  # messages:
  #   basename: messages/exception
    # encoding: UTF-8 
  #DB 설정
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb  
    hikari:
      driver-class-name: org.h2.Driver  
  #JPA 설정
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: debug
  config: src/main/resources/logback-spring.xml
  
